# This is a basic workflow that is manually triggered

name: Add new journal entry

on: workflow_dispatch

jobs:
  today_journal_entry:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "America/New_York"
    - name: Run script file
      run: |
         ./journal/today_entry.sh
      shell: bash
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
